export {
  INJECTION_MODULES,
  INJECTION_MODULE_MAP,
  buildAndonFromFailedStartup,
  buildBatchTraceLinks,
  buildInjectionCode,
  buildInjectionRecordPayload,
  buildLabelPayload,
  buildPurchaseRequisitionSuggestion,
  buildStartupCheckResult,
  calculateInjectionOee,
  canStartProductionFromInjectionGates,
  getInjectionModuleByKey,
  getInjectionModuleByResource,
  getInjectionNextActions,
  injectionStatusText,
  isEightDComplete,
  summarizeComplaint8d,
  summarizeInjectionRecords,
  summarizeMoldMaintenancePlan,
  validateInjectionRecord,
  type InjectionAction,
  type InjectionFieldType,
  type InjectionFormField,
  type InjectionModuleDefinition,
  type InjectionModuleKey,
} from '../../../frontend-admin/src/utils/injection-professional.ts'
